"""empty message

Revision ID: 2bd339a37037
Revises: 9e99bd1decae
Create Date: 2016-02-22 03:29:54.040538

"""

# revision identifiers, used by Alembic.
revision = '2bd339a37037'
down_revision = '9e99bd1decae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    ### end Alembic commands ###
