"""empty message

Revision ID: 4897923f45be
Revises: a1a93cccae75
Create Date: 2016-02-19 18:29:29.365944

"""

# revision identifiers, used by Alembic.
revision = '4897923f45be'
down_revision = 'a1a93cccae75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cvc', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('expiration', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiration')
    op.drop_column('users', 'cvc')
    ### end Alembic commands ###
