"""empty message

Revision ID: a1a93cccae75
Revises: fdfeab0171cb
Create Date: 2016-02-19 17:29:41.627057

"""

# revision identifiers, used by Alembic.
revision = 'a1a93cccae75'
down_revision = 'fdfeab0171cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('card_number', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'card_number')
    ### end Alembic commands ###
